# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS
S3_ASSET_URL: "s3.amazonaws.com"
AWS_REGION: 'us-east-1'
GROUPDOCS_PUBLIC: 'xxxxxxxxxxxxxxxx'
GROUPDOCS_PRIVATE: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

development:
  AWS_BUCKET: 'weblish-dev'
  AWS_ACCESS_KEY_ID: 'xxxxxxxxxxxxxxxxxxxx'
  AWS_SECRET_ACCESS_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

production:
  AWS_BUCKET: 'weblish'
  AWS_ACCESS_KEY_ID: 'xxxxxxxxxxxxxxxxxxxx'
  AWS_SECRET_ACCESS_KEY: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
